apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ruby-gh-test
    app.kubernetes.io/name: ruby-gh-test
  name: ruby-gh-test
  namespace: ruby-gh-test
spec:
  ports:
  - name: http
    port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app.kubernetes.io/instance: ruby-gh-test
    app.kubernetes.io/name: ruby-gh-test
  type: NodePort
